# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c34d320316c1d54e893091561073b98b3d00f0f602300c88256465bff2d767301d329f7ed98682d656b95f3a9b8bd63c92457053f61bc7f942799c72087beb3e

test:
  secret_key_base: 6b38957931965e2548ea04bd7fae0e4d76d204a0b6605261abd45485950abd8dc5168a8a4fbddddeb335747dbc10fc6147660932e12013fd794059f7056118a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
